name: scrawler
description: A Simple Nextcloud Note Client App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.6+57

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_markdown: ^0.7.3+1
  
  http: ^1.2.0
  intl: ^0.20.2
  shared_preferences: ^2.0.13
  
  url_launcher: ^6.3.1
  universal_platform: ^1.1.0

  flutter_svg: ^2.0.10+1
  material_symbols_icons: ^4.2784.0
  provider: ^6.1.5+1
  easy_localization: ^3.0.7+1
  nextcloud: ^9.0.0
  file_picker: ^10.3.3
  forui: ^0.20.3
  sqflite: ^2.4.2
  path: ^1.9.1
  image_picker: ^1.2.1

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "images/scrawler-desktop.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/scrawler.png"
    background_color: "#FFFFFF"
    theme_color: "#5EAAA8"
  windows:
    enable: true
    image_path: "images/scrawler-desktop.png"
    icon_size: 256 # min:48, max:256, default: 48
  platforms:
    macos:
      enable: true
      image_path: "images/scrawler-desktop.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  icons_launcher: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - images/scrawler.png
    - images/scrawler-desktop.png
    - images/google.png
    - images/undraw_friends_xscy.svg
    - images/undraw_random-thoughts_goca.svg
    - assets/translations/